name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your ideal solution.
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Dashboard
        - Transactions
        - Portfolio
        - FIRE Calculator
        - Charts & Visualization
        - API / Backend
        - CI/CD & Deployment
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have
        - Important
        - Critical
    validations:
      required: true
